name: Github CI
run-name: run by ${{ github.actor }}
on:
    - push
    - workflow_dispatch


jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    
    steps:
        - name: Checkout
          uses: actions/checkout@v3.5.2     

        - name: Setup Python
          uses: actions/setup-python@v4.6.0

        - name: Install Dependencies
          shell: bash
          run: |
            python -m venv venv
            . venv/bin/activate
            cd App
            pip install -r requirements.txt
        
        - name: run tests
          run: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            cd Tests
            pytest -v  test_app.py

        