name: Github CI
run-name: run by ${{ github.actor }}
on:
    - push
    - workflow_dispatch


jobs:
  build:
    name: Build
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    
    steps:
        - name: Checkout
          uses: actions/checkout@v3.5.2     

        - name: Setup Python
          uses: actions/setup-python@v4.6.0

        - name: Install Dependencies
          shell: bash
          run: |
            python -m venv venv
            . venv/bin/activate
            cd App
            pip install -r requirements.txt
        - name: Configure AWS Credentials For GitHub Actions
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ vars.AWS_REGION }}
        
        - name: run tests
          run: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v  --cov

        - name: Git Semantic Version
          uses: PaulHatch/semantic-version@v5.0.3
          id: repo_sem_ver
          with:
            tag_prefix: "v"
            major_pattern: "(MAJOR)"
            minor_pattern: "(MINOR)"
            version_format: "${major}.${minor}.${patch}-prerelease${increment}"
            change_path: "./"
            namespace: repository
            bump_each_commit: true
            search_commit_body: true
            user_format_type: "csv"  
          #if: ${{ github.ref == 'refs/heads/main' }} 

        - name: Tag Release (vX.Y.Z)
          run: |
            git tag ${{ steps.repo_sem_ver.outputs.version_tag }}
            git push origin ${{ steps.repo_sem_ver.outputs.version_tag }}
          #if: ${{ github.ref == 'refs/heads/main' }}

        - name: Application Version
          id: version
          uses: paulhatch/semantic-version@v5.0.3
          with:
            tag_prefix: "v"
            major_pattern: "(MAJOR-APP)"
            minor_pattern: "(MINOR-APP)"
            version_format: "${major}.${minor}.${patch}-prerelease${increment}"
            change_path: "./App"
            namespace: app
            bump_each_commit: false
            search_commit_body: true
            user_format_type: "csv"
          #if: ${{ github.ref == 'refs/heads/main' }}

        - name: Create App release
          uses: thedoctor0/zip-release@0.7.1
          with:
              type: "zip"
              filename: "App-release-${major}.${minor}.${patch}.zip"
              exclusions: "*.git* /*node_modules/* .editorconfig */Release"
              directory: "./App"
              path: "./"
          #if: ${{ github.ref == 'refs/heads/main' }}

        - name: Create Release
          uses: ncipollo/release-action@v1.12.0
          with:
            artifactErrorsFailBuild: true
            commit: true
            generateReleaseNotes: true
            makeLatest: true
            tag: ${{ steps.repo_sem_ver.outputs.version_tag }}
        
          #if: ${{ github.ref == 'refs/heads/main' }}


        